export const APPLE_MAINNET_REDIRECT_URI_V2 = process.env.NEXT_PUBLIC_APP_APPLE_MAIN_REDIRECT_URI_V2;
export const APPLE_MAINNET_REDIRECT_URI = process.env.NEXT_PUBLIC_APP_APPLE_MAIN_REDIRECT_URI;

export const APPLE_TESTNET_REDIRECT_URI_V2 = process.env.NEXT_PUBLIC_APP_APPLE_TESTNET_REDIRECT_URI_V2;
export const APPLE_TESTNET_REDIRECT_URI = process.env.NEXT_PUBLIC_APP_APPLE_TESTNET_REDIRECT_URI;

export const PORTKEY_VERSION = 'v2';
